module.exports = {
  AUTO_REPRICING: "AUTO_REPRICING",
  DISPUTE_CASES: "DISPUTE_CASES",
  ESCROW_SUPPORT: "ESCROW_SUPPORT",
  CUSTOM_DOMAIN: "CUSTOM_DOMAIN",
  BRANDED_INVOICE_TEMPLATES: "BRANDED_INVOICE_TEMPLATES",
  ROLEX_VERIFICATION: "ROLEX_VERIFICATION",
};
